### ISSUE TITLE
report-aggregate-module fails for submodules without tests

### ISSUE THREAD

**Issue by gmuecke** [hcoles/pitest#467] opened 2018-05-09 14:08 UTC
**Context**
We have a multi-module project where I'd like to run the report-aggregate-module goal.
Some of the submodules don't have any tests (i.e. api modules)

When I run on the root module (after I built the project with pitest:mutationCoverage):
```
mvn pitest:report-aggregate-module
```

**Observed Behavior**
The goal fails with one of the following error message

project has no `src/test` folder at all
```
[ERROR] Failed to execute goal org.pitest:pitest-maven:1.4.0:report-aggregate-module (default-cli) on project xxx: An error has occurred in PIT Test Report report generation. xxx\submodule\src\test\java does not exist or is not a directory -> [Help 1]
```
or if project has an empty `src/test` folder
```
[ERROR] Failed to execute goal org.pitest:pitest-maven:1.4.0:report-aggregate-module (default-cli) on project xxx: An error has occurred in PIT Test Report report generation. xxx\submodule\target\test-classes does not exist or is not a directory -> [Help 1]`
```

**Expected behavior**
The goal execution should succeed, assuming 0 mutations for these modules.

**Comment by maxgabut** [comment] 2018-05-28 07:20
@gmuecke #466 is now merged. Could you confirm that it fixes you problem ? If so, we can close this issue.

**Comment by maxgabut** [comment] 2018-05-30 20:50
I guess that getting a new error is [progressing](https://www.commitstrip.com/en/2018/05/09/progress/) (:

In order to make aggregation work, I had to configure the plugin this way :
```xml
<plugin>
    <groupId>org.pitest</groupId>
    <artifactId>pitest-maven</artifactId>
    <version>1.4.1-SNAPSHOT</version>
    <configuration>
        <!-- generate line coverage -->
        <exportLineCoverage>true</exportLineCoverage>
        <!-- in the "right" format -->
        <outputFormats><value>XML</value></outputFormats>
        <!-- and write reports where report-aggregate-module expects to find it -->
        <timestampedReports>false</timestampedReports>
    </configuration>
    <executions>
        <execution>
            <id>run-mutation-tests</id>
                <goals>
                    <goal>mutationCoverage</goal>
                </goals>
        </execution>
     </executions>
</plugin>
```

I hope it helps.

**Comment by gmuecke** [comment] 2018-06-04 15:36
Ok, I added the  `<exportLineCoverage>true</exportLineCoverage>` (isn't that supposed to be the default?) ... anyhow, now I get this error:

```
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: org.apache.maven.plugin.MojoExecutionException: An error has occurred in PIT Test Report report generation.
	at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:83)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 21 more
Caused by: org.apache.maven.reporting.MavenReportException: null
	at org.pitest.maven.report.PitReportAggregationModuleMojo.executeReport(PitReportAggregationModuleMojo.java:87)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:131)
	at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:76)
	... 23 more
Caused by: java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.pitest.aggregate.MutationResultDataLoader.mapToData(MutationResultDataLoader.java:44)
	at org.pitest.aggregate.MutationResultDataLoader.mapToData(MutationResultDataLoader.java:17)
	at org.pitest.aggregate.DataLoader.loadData(DataLoader.java:67)
	at org.pitest.aggregate.DataLoader.loadData(DataLoader.java:45)
	at org.pitest.aggregate.ReportAggregator.aggregateReport(ReportAggregator.java:52)
	at org.pitest.maven.report.PitReportAggregationModuleMojo.executeReport(PitReportAggregationModuleMojo.java:85)
	... 25 more
```

**Comment by maxgabut** [comment] 2018-06-05 09:03
exportLineCoverage defaults to `false` (see [it's definition in AbstrastratPitMojo.java](https://github.com/hcoles/pitest/blob/621a3b225415d7b2e15e3e415a2c586bc9fb26bc/pitest-maven/src/main/java/org/pitest/maven/AbstractPitMojo.java#L231)).

For you new failure, I don't really see the cause. Could you publish a sample of code reproducing it ?

**Comment by maxgabut** [comment] 2019-01-20 20:39
@gmuecke I'm closing this issue as it has been around without activity for some time now. Sorry I couldn't help you out. Don' t hesitate to comment here again if you have more data to provide.

**Closed by maxgabut** 2019-01-20 20:39 UTC
