### ISSUE TITLE
HTML generation doesn't show the code

### ISSUE THREAD

**Issue by AnakinPt** [hcoles/pitest#754] opened 2020-04-13 14:14 UTC
When I run the gradle plugin, using version 1.4.8, the HTML report doesn't show the code.

I'm using this configuration:
pitest {
    excludedClasses = ["someClass"]
    testPlugin = 'junit5'
    junit5PluginVersion = '0.12'
    verbose = true
    timestampedReports = false
    mutationThreshold=60
}

Do I need to pass any extra parameter?

And this also doesn't run in Windows, because of the large command line for the javaExec. is there a way to fix this?

**Comment by szpak** [comment] 2020-04-13 14:20
Most likely this is a duplicate of https://github.com/szpak/gradle-pitest-plugin/issues/198. To confirm you can switch back to 1.4.7 which should "fix" it. In that case you can close the issue here as it is the Gradle plugin specific.

**Comment by AnakinPt** [comment] 2020-04-16 09:31
I tried with 1.4.7 and doesn't work.

**Comment by davidburstrom** [comment] 2020-05-21 17:35
@AnakinPt As for your classpath issue on Windows, the Gradle plugin has support for `useClasspathFile = true` which should solve your issue.

**Comment by szpak** [comment] 2020-05-21 20:27
@AnakinPt Please try again with the latest 1.5.1. There is a [functional test](https://github.com/szpak/gradle-pitest-plugin/blob/3ad30e3f9fb379919d7fec2bb65dfc0fbc654cd4/src/funcTest/groovy/info/solidsoft/gradle/pitest/functional/PitestPluginGeneralFunctionalSpec.groovy#L110-L112) for source code available in HTML reports which passes on Linux, Mac and Windows. Therefore, if you still has a problem in your project please prepare [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) as you might hit some corner case.

@davidburstrom `useClasspathFile = true` might help in the situation the classpath used in the project is too long for the maximum allowed number of chars in Windows. I'm not sure if it is a case here.

**Closed** 2024-04-02 15:24 UTC
