### ISSUE TITLE
False error: Mutation testing requires a green suite

### ISSUE THREAD

**Issue by Kidlike** [hcoles/pitest#170] opened 2015-02-10 18:05 UTC
I am running pitest against a green suite.
Though specific test classes fail when run with pitest.

The failing test classes have the following annotations:

```
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = "/domain-test-context.xml")
```

This setup is being used so that we test code against a real DB.

If I am not mistaken these annotations is the reason these classes fail when being run by pitest.

Is this solveable ?

If not then is it possible to somehow configure pitest to ignore such tests ?

**Comment by Kidlike** [comment] 2015-02-10 18:08
When I say ignore such tests, I mean have a section in the pitest configuration like the `avoidCallsTo`. Something like `ignoreTestsThatUse`.

**Comment by hcoles** [comment] 2015-02-12 09:33
Pitest has no problem with spring annotations that I'm aware of, but if these tests are hitting a real db then they are not suitable for mutation testing as they unlikely to be repeatable.

Tests can be excluded using the excludeClasses option.

There isn't currently a built in way to exclude tests by annotation - although pitest does have partial support for junit categories that could be used for this purpose.

**Comment by Kidlike** [comment] 2015-02-12 10:34
jUnit categories seem interesting. Thanks !

***About the actual fail :***

I should have posted this from the beginning.
It throws this for several test cases:
```
5:52:59 PM PIT >> FINE : SLAVE : FAIL Description [testClass=com.company.propagation.domain.DataQueueSpringTest, name=testSerializationAndDeserialization(com.company.propagation.domain.DataQueueSpringTest)] -> java.lang.IllegalStateException: Failed to load App
```

And yes, the tests that are failing have these annotations, and are hitting a real db.
About the repetition, the db is cleared in the `@After` section. Shouldn't that be sufficient ?

**Comment by KyleRogers** [comment] 2015-02-17 21:05
That depends on several possibilities:
- if you run pitest with more than 1 thread those tests might still interfere with each other
- if the cleanup code is part of the production code it might get mutated and clean up might fail
- it might not be the database but the file system or another shared resource which is not well isolated


Nevertheless the line you've postet ends with "Failed to load App[lication Context]" which is more a sign that the integration test(s) couldn't start at all. Maybe the database is not ready yet, maybe there are class path issues or maybe there is another problem.

In my opinion mutating integration tests - and if you hit a database those tests are integration tests not unit tests - is dangerous because those tests are designed to interact with the environment (file system, database, ...) and you cannot tell what a mutant might do to those resources. Maybe one of the mutants erases the whole file system....

**Comment by Kidlike** [comment] 2015-02-17 22:10
I totally agree with not running such tests, and I will not.
But as you said, the mutation testing doesn't even start.
It fails when still calculating the coverage.
Everything is OK when running the tests normally or calculating coverage with cobertura.

I am just trying to figure out why is this happening.
We 've had a similar issue before because of multiple instrumentations on the same classes.
So maybe there's a conflict between what spring does, and what pitest does.

Anyway, I will not investigate this further, as I will not be mutating these tests.

Feel free to close this :)

**Comment by bobbylough** [comment] 2015-06-11 15:05
I have experienced the same situation on two of my test classes.  There is nothing unique about the test classes so I really hope that progress has been made on debugging this issue.

**Comment by GrzesiekP** [comment] 2015-06-15 07:31
@bobbylough Yeah, i'm randomly getting the same error:

```
Failed to execute goal org.pitest:pitest-maven:1.1.5:mutationCoverage (mutation-coverage-goal) on project xxx: 
Execution mutation-coverage-goal of goal org.pitest:pitest-maven:1.1.5:mutationCoverage failed: 
All tests did not pass without mutation when calculating line coverage. 
Mutation testing requires a green suite.
```

And this is when all my tests pass. It started happening to me when I upgraded from maven 3.2.5 to 3.3.3

**Comment by akhayrutdinov** [comment] 2015-07-05 09:56
> Tests can be excluded using the excludeClasses option

@hcoles, actually the property is called ```excludedClasses``` (see it here: https://github.com/hcoles/pitest/blob/master/pitest/src/main/java/org/pitest/mutationtest/config/ConfigOption.java#L99). There is the same misspelling error on the FAQ page (http://pitest.org/faq/).

**Comment by galovics** [comment] 2016-07-06 06:52
Is there any update here?

The data access layer testing is impossible without the Spring based tests and unfortunately there are projects which don't have the data access tests within one package, thus it's really really hard to skip those tests.
Besides that, there are other tests which can't be tested without setting up the spring context; for example AOP testing.

I would really appreciate an option to use some test filtering based on the test's runner.

**Comment by Kidlike** [comment] 2016-07-06 09:45
@galovics, Personally, I rely on the naming of such classes, which is "SomethingDao", or "SomethingDAO", depending on your preference (I go with the first one).

So then you can add a pattern to exclude all of these from pitesting.
I also add our legacy "infrastructure" package name in another pattern, to exclude any legacy data access classes from pitesting.

**Comment by galovics** [comment] 2016-07-06 10:30
@Kidlike yep, thats true and that's what I'm using as a naming convention. However, there are a lot of other cases when you need spring based tests with varying package names. Excluding them one-by-one is an extremely painful task.

Even if you have to create new ones, you have to exclude them explicitly which gives another complexity to the problem.

**Comment by Kidlike** [comment] 2016-07-06 10:51
Well, I agree in concept, that pitest needs what you suggested. I would find that very useful too.
That being test runner based filtering.
Or, ideally, filtering on any annotation on the test classes.

Anything else is a workaround.

**Comment by galovics** [comment] 2016-07-06 12:49
Hopefully [this](https://github.com/hcoles/pitest/pull/283) pull request extends the functionality to support this. :-)

**Comment by KyleRogers** [comment] 2016-07-07 18:38
We're using a naming convention as well. All tests ending just in *Test are considered unit tests and will be executed by surefire and qualify as tests for pitest.

Tests that access the file system, database etc. are considered integration tests and are end with *IntegrationTest. Those tests won't be run by surefire but will be run with failsafe. These tests usually take times longer than usual unit tests and kick of small to medium sized spring application contexts. Thus we sometimes want to skip them during maven build. The naming convention is also a good fit for pitest.

But I understand that this is not a model for everyone. Maybe the runner exclusion is worth a try.

I usually don't think mutating integration tests is a good idea because they do not run isolated in memory but access their environment (file system, database etc.) and introducing arbitrary errors might harm those systems.
On the other hand this thread/issue shows another short coming: Although pitest reports that there is an error in your tests it's really hard to debug the issue and find the root cause (is it the database? a shared port 8080? ....). Maybe we should improve that as well.

**Comment by KyleRogers** [comment] 2016-07-07 19:18
While reviewing the change I came across a limitation of the [pull request](https://github.com/hcoles/pitest/pull/283) :

This works if and only if you're using a Runner, e.g. SpringJUnit4ClassRunner. The trend is more towards using rules for that purpose instead of runners (rules allow you to combine a Parameterized Runner with a Spring test setup). Thus if one day one of your team members decides to replace the runner with a rule you're in trouble again.

If you can't use a naming schema as described in my previous coment you might use JUnit categories as already proposed by @hcoles . Have you already tried JUnit categories?

**Comment by galovics** [comment] 2016-07-08 07:40
I haven't used rules for this purpose but if this is the trend, it can be supported as well. I like to do small steps to the goal and this is the first one (excluding by runners). Let's see how it works and how people use it, then we can continue developing this option.

I heard about JUnit categories as well but if you have hundreds or thousands of tests, you don't want to categorize them one-by-one; but yeah, this might be an option for other projects.

**Comment by gluckzhang** [comment] 2020-10-30 14:32
> Tests can be excluded using the excludedTestClasses option.

May I ask if there is a way to exclude some test cases in a class instead of the whole test class? It seems that I am only able to specify classes using `excludedTestClasses` option. Thanks!

**Comment by StefanPenndorf** [comment] 2020-12-07 20:12
@gluckzhang I can't remember any. But if your tests must be excluded they might share a common property or issue. Maybe it's a good hint to separate test classes by that property? This is just an idea because I don't know your concrete scenario... -- If you still have the question it might be worth opening a new issue or asking on the mailing list.

@hcoles Is that issue solved here? Couldn't get a clue if there is still a problem left and couldn't find out what would be needed to close this rather old issue. Maybe you close it and anybody who feels that there is something left to do can open a new issue and describe her concrete situation. What do you think?

**Comment by gluckzhang** [comment] 2020-12-07 20:44
Hi @StefanPenndorf , thanks for the reply! I directly add `@Ignore` for these methods as there are only a few methods to be excluded. I will see if this manual work becomes a burden. If so I will open a new issue for further discussion :)

ps: my concrete scenario is that I am doing some research on different projects using mutation testing, but some projects do have many failed test cases in a specific version (maybe because of my local environment). I actually don't know the exact reason for such failures. So ideally, that would be cool if I can directly specify these methods in `pom.xml` as a configuration for pitest. Anyway, I am available to the source code and I can add `@Ignore` to skip these cases.

**Comment by hcoles** [comment] 2020-12-08 10:30
@StefanPenndorf I agree we should close this one. I think there may be a feature request in here to support filtering out tests that use certain junit rules, but I think that can be raised seperately if it is still something people would find useful in 2020.

**Closed by hcoles** 2020-12-08 10:30 UTC
