### ISSUE TITLE
Increment Analysis Issue

### ISSUE THREAD

**Issue by Yuvarajahbk** [hcoles/pitest#763] opened 2020-05-05 13:35 UTC
Increment analysis is not working correctly.

				<plugin>
				<groupId>org.pitest</groupId>
				<artifactId>pitest-maven</artifactId>
				<version>1.4.11</version>
				<configuration>
					<testPlugin>testng</testPlugin>
					<verbose>true</verbose>
					<features>
						<value>+EXPORT</value>
					</features>
					<targetClasses>
						<param>com.dt.appservice.*</param>
					</targetClasses>
					<historyInputFile>${project.basedir}\\test-output\\PitestHistory\\history.txt</historyInputFile>
					<historyOutputFile>${project.basedir}\\test-output\\PitestHistory\\history.txt</historyOutputFile>
					<targetTests>
						<param>com.abc.dtc.service.*</param>
					</targetTests>
					
						</configuration>
					<plugin>

It is creating history file  but not referring  for next run.. When I am running same set of files without  any modifications, It is taking same time. No performance improvement.

could you help me on this?

**Comment by StefanPenndorf** [comment] 2020-05-06 15:08
I could reproduce this issue with a minimal example project using maven and testng. The problem is the combination of different granularity of the coverage calculation which triggers on a "by test class" basis, but reports covered tests "by test method" (for history calculation) on the one hand and the history check which in turn acts on a "by test class" basis. Those different definitions of a TestUnit seem to collide for testng.

I'll try to provide a fix for this.

**Closed** 2020-05-10 14:18 UTC

**Comment by Yuvarajahbk** [comment] 2020-05-15 03:07
Hello,

Thank you for your response and fixing the issue ASAP.

I tried to test it by check out the code but I am unable to do set up as I
am working on company's environment. It is throwing error " unable to find
artifact org.pitest:pitest:pitest:jar1.5.2-SNAPSHOT in nexus". Really
helpful if you  could you share that plugin which have the fix  or when
would be the next release date, so that I can use it

Thanks in advance

Regards,
Yuvaraja

**Comment by StefanPenndorf** [comment] 2020-05-23 13:43
Hi Yuvaraja,

did you build the project using ```mvn clean install``` ? This should install the current snapshot version into your lokal ```.m2``` directory. Thus no need for maven to query your company's nexus respository.

I'm afraid only @hcoles can tell you about the release date of the next pitest version.
