### ISSUE TITLE
Provide documentation/way to add custom mutations

### ISSUE THREAD

**Issue by dalewking** [hcoles/pitest#859] opened 2021-02-07 00:23 UTC
This may be more of a question than an issue, but I was wondering if there was an easy way to create custom mutants specific to your code.

For example, our code base has our own version of a Result monad that represents a success or failure. It would be nice to have a mutant that if a function returns a successful result it replaces it with an error result to verify that the tests are handling errors.

But I can't find an easy way to do that. The standard mutations are not going to handle that case because it knows nothing about the custom type. I assume it would have to be a plugin of some kind, but the documentation for plugins talk about filtering mutations, but not really about new mutations.

**Comment by hcoles** [comment] 2021-02-07 09:43
At the moment it is not possible to plugin in new mutation operators, just complete mutation engines. I agree this would be a good feature to have, unfortunately it would require reworking a lot of code and tests due to some bad decisions made early on.

**Comment by dalewking** [comment] 2021-02-07 16:25
Looking into it some more I am not sure it is so hard. The key class is org.pitest.mutationtest.engine.gregor.config.Mutator. Right now that has a static block that does a bunch of calls to add and addGroup. If you instead provided a plug-in architecture for a library where you pass an interface to the plug-in where that interface has the add and addGroup methods then a plug-in could add its own mutations and groups of mutations. It would be great to refactor the existing mutations into its own plug-in library or libraries (e.g. experimental could be a separate library) but that isn't a necessary first step.

**Comment by oscarlvp** [comment] 2021-03-11 13:36
@dalewking take a look at https://github.com/STAMP-project/pitest-descartes if you want to try to build your own mutation engine. The code is simpler as we implement only method-level mutation operators that completely rewrite the methods. Also, I would like to know a bit more about your use case. We want to support custom and plugable mutation operators in the engine.

**Comment by oscarlvp** [comment] 2021-03-23 12:49
Check out a new mutation engine for that : https://github.com/oscarlvp/pitest-extensible-engines. It is functional but, it is still a work in progress.

**Comment by hcoles** [comment] 2021-11-12 16:37
Closing as mutation operator extentsion point added in release 1.7.0.

**Closed by hcoles** 2021-11-12 16:37 UTC

**Comment by halcyonsoul3** [comment] 2024-06-19 08:54
Hi @hcoles ,
As suggested here https://pitest.org/quickstart/advanced, we tried implementing **custom-mutator** for our java-maven project by adding below plugin and dependencies.
Yet i am facing below error, can you please add proper documentation on creating custom-mutator.

**ERROR:
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.pitest:pitest-maven:1.16.1:mutationCoverage failed: Mutator or group MyCustomMutator is unknown. Check PIT configuration and try again.**

<dependency>
<groupId>org.pitest</groupId>
<artifactId>pitest-maven</artifactId>
<version>1.16.1</version>
</dependency>

<plugin>
<groupId>org.pitest</groupId>
<artifactId>pitest-maven</artifactId>
<version>1.16.1</version>
<configuration>
</configuration>
<dependencies>
<dependency>
<groupId>org.pitest</groupId>
<artifactId>pitest-junit5-plugin</artifactId>
<version>1.2.1</version>
</dependency>
</dependencies>
</plugin>
