### ISSUE TITLE
Unable to create directory

### ISSUE THREAD

**Issue by Pluriscient** [hcoles/pitest#530] opened 2018-10-23 17:09 UTC
After adding PITest to my maven pom; I try to run it and get the attached stacktrace.
```

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:56 min
[INFO] Finished at: 2018-10-23T19:00:23+02:00
[INFO] Final Memory: 11M/389M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.pitest:pitest-maven:1.4.3:report (default-cli) on project Pinball4: Execution default-cli of goal org.pitest:pitest-maven:1.4.3:report failed: no report generators executed successfully
[ERROR] 
[ERROR] Please copy and paste the information and the complete stacktrace below when reporting an issue
[ERROR] VM : Java HotSpot(TM) 64-Bit Server VM
[ERROR] Vendor : Oracle Corporation
[ERROR] Version : 25.171-b11
[ERROR] Uptime : 118443
[ERROR] Input ->
[ERROR] 1 : -Dmaven.multiModuleProjectDirectory=C:\cs\y2\sem\pinball-4
[ERROR] 2 : -Dmaven.home=C:\Users\erict\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\182.4505.22\plugins\maven\lib\maven3
[ERROR] 3 : -Dclassworlds.conf=C:\Users\erict\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\182.4505.22\plugins\maven\lib\maven3\bin\m2.conf
[ERROR] 4 : -javaagent:C:\Users\erict\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\182.4505.22\lib\idea_rt.jar=55571:C:\Users\erict\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\182.4505.22\bin
[ERROR] 5 : -Dfile.encoding=UTF-8
[ERROR] BootClassPathSupported : true
[ERROR] -> [Help 1] 
```

The configuration for the plugin looks like this:
```
<plugin>
                <groupId>org.pitest</groupId>
                <artifactId>pitest-maven</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>
                                report
                            </goal>
                        </goals>
                    </execution>
                </executions>
                <version>1.4.3</version>
            </plugin>
```

[bugreport.txt](https://github.com/hcoles/pitest/files/2507147/bugreport.txt)

**Comment by maxgabut** [comment] 2019-02-16 17:13
I tried to reproduce the issue but couldn't. I'm closing it, because I don't think we have enough information to go further. Fell free to add comment if you have more info about this issue.

**Closed by maxgabut** 2019-02-16 17:13 UTC
