### ISSUE TITLE
Make pitest ignore the coverage of synthetic methods?

### ISSUE THREAD

**Issue by skapral** [hcoles/pitest#420] opened 2017-11-23 23:18 UTC
I have a class, covered by tests on 100% line and mutation coverage. Using Javassist, I generated one static private synthetic method there. As a consequence, I got line coverage drastically reduced - pitest reports much more branches to cover than it was before adding synthetic method. Mutation coverage for that class remains the same. It seems like Pitest is trying to measure synthetic methods also.

Adding newly added synthetic method to "excludeMethods" list changes nothing. Pitest version is 1.2.4.

Could you please give a hint on how and where the line coverage is gathered? Isn't this logic supposed to ignore synthetic methods?

PS: For now I don't have the case localised. I'll localize it a bit later if it is needed.

**Comment by skapral** [comment] 2017-11-23 23:34
Seems like I found an answer to my first question. Adding a quick hack to `org.pitest.classinfo.BridgeMethodFilter` to ignore the methods with ACC_SYNTHETIC attributes solved my problem. So - the second question remain: Isn't it worth to replace or enhance `BridgeMethodFilter` with new `SyntheticMethodFilter`?

**Comment by hcoles** [comment] 2017-11-24 09:55
It's not quite as simple as that - there are corner cases where pitest needs to gather the coverage for synthetic methods, for example Java 8 will place some code from lambdas that should be eligible for mutation into synthetic methods. 

I think lambdas may now be the only corner case. This filtering code pre-dates Java 8 (and probably Java 7 and possibly Java 6), I think the original reason it didn't filter all synthetic methods may have been to try and support Scala but it could be there are some other cases in Java I have forgotten.

Either way there is no reason that this couldn't be tightened. Assuming there are no additional cases I think the correct implementation would be:-

```java
isSynthetic() && !name.startsWith("lambda$");
```

**Comment by skapral** [comment] 2017-11-24 13:04
I also thought of another possible solution. Instead of filtering methods by synthetic flag, filter them by the absence of line number table (maybe make an option for enabling/disabling it). Like, what is the reason to calculate coverage for methods that don't have line numbers if they won't produce any readable feedback in reports anyway.

**Comment by TomRK1089** [comment] 2021-08-04 16:44
I hate to revive such an old thread, but this feels applicable to records as well. The accessor methods for a record's fields are generated by the compiler -- mutating them provides 0 value in the overall report. I can't easily exclude all record types because they won't have some consistent naming convention.

**Comment by hcoles** [comment] 2021-08-04 16:51
@TomRK1089 If you can put an example project together that reproduces the issue I can take a look. Although this issue is still open pitest ought to already be filtering out code marked as synthetic, so something more may be required for records.

**Comment by TomRK1089** [comment] 2021-08-04 18:55
I'll put one together. In the meantime here's a screenshot from the report that spurred this comment (with identifying package info omitted): 
![image](https://user-images.githubusercontent.com/3771242/128238772-235747f8-26ca-4cab-a597-275c3f74aed7.png)

For some reason I also thought Pitest automatically skipped mutating equals/hashcode/toString as well?

**Comment by TomRK1089** [comment] 2021-08-04 19:16
Did a clean Maven build and toString and friends are now excluded properly, so I will attach a sample project later this week demonstrating the record issue.

**Comment by hcoles** [comment] 2021-08-05 12:58
@TomRK1089 

Taken a look at records, junk should be filtered once this branch is merged -> https://github.com/hcoles/pitest/pull/919

**Closed** 2022-03-02 12:11 UTC
